main:
  tasks:
    - path: btc-price-postprocessed.json
      schema:
        fields:
          - name: currency
            type: string
          - name: bitcoinRate
            type: number
            constraints:
              maximum: 40000
